### PR TITLE
feat: add mol-fe specific config

### PR DESCRIPTION
**Pull request by carpasse**
- Enable template literals
- Enable shorthand arrow funcs
- Enable commonjs imports
- Disable strict checking
- Enable native promise
- Disable lodash typechecking

### CODE REVIEW

**Comment by carpasse** [comment]
I agree with all the proposed rules and I would suggest some others.
I've kept the original value and added a comment with my thoughts or a proposed value change

``` javascript
"array-callback-return": 2,         // enforce return statements in callbacks of array methods
                                    // ??? Will this work with shorthand arrow functions?

"consistent-return": 2,             // require return statements to either always or never specify values
                                    // Doesn't this rule conflicts with "callback-return" style rule?? 
                                    // I see the value on enforcing return or not returning it (NOT SURE ABOUT THIS ONE)

"consistent-this": [                // enforce consistent naming when capturing the current execution context
    2,
    "self"                          // We can not use "self" it has a meaning on the browsers, use _this instead
],

"generator-star-spacing": [         // enforce consistent spacing around * operators in generator functions  [AUTOFIX]
   0,                               // Souldn't it be error?
   { 
     "after": false,
     "before": true
   }
],

"import/default": 2,               // Ensure a default export is present, given a default import.
                                   // Won't we get a lot of false possitive with this rule on projects that don't use import/export?


"import/imports-first": [          // UNKNOWN RULE  <==== where is this rule
  2,
  {
    "absolute-first": true
  }
],

"import/no-namespace": 2,          // Report namespace imports
                                   // See no reason for forbidding namespaces on imports

"lines-around-comment": [          // require empty lines around comments  [AUTOFIX]
  2,
  {
    "beforeBlockComment": false,   // I would actually do the opposite 
    "beforeLineComment": false     // I would actually do the opposite 
  }
],


"no-path-concat": 2,               // disallow string concatenation with __dirname and __filename
                                   // Change to 0

"no-process-env": 2,               // disallow the use of process.env
                                   // Change to 0

"object-curly-spacing": [         // enforce consistent spacing inside braces  [AUTOFIX]
  0,
  "never"                         // We have been enforcing it up until now [2, "always"]
]
```

**Comment by claudiorodriguez** [comment]
```
"array-callback-return": 2,         // enforce return statements in callbacks of array methods
                                    // ??? Will this work with shorthand arrow functions?
```

Return is implicit in shorthand, so yes.

```
"consistent-return": 2,             // require return statements to either always or never specify values
                                    // Doesn't this rule conflicts with "callback-return" style rule?? 
                                    // I see the value on enforcing return or not returning it (NOT SURE ABOUT THIS ONE)
```

No it doesn't conflict. You just can't do `return;` which is a good thing generally.

```
"consistent-this": [                // enforce consistent naming when capturing the current execution context
    2,
    "self"                          // We can not use "self" it has a meaning on the browsers, use _this instead
],
```

A valid point.

```
"generator-star-spacing": [         // enforce consistent spacing around * operators in generator functions  [AUTOFIX]
   0,                               // Souldn't it be error?
   { 
     "after": false,
     "before": true
   }
],
```

It could be overriding an inherited rule, but I guess it should.

```
"import/default": 2,               // Ensure a default export is present, given a default import.
                                   // Won't we get a lot of false possitive with this rule on projects that don't use import/export?
```

No. I am using this config on mol-fe-legal-api, which is commonjs, without problems.

```
"import/imports-first": [          // UNKNOWN RULE  <==== where is this rule
  2,
  {
    "absolute-first": true
  }
],
```

No idea.

```
"import/no-namespace": 2,          // Report namespace imports
                                   // See no reason for forbidding namespaces on imports
```

Their transpiler implementation is a bit wonky. I don't like `import * as ...` myself. But we could enable it.

```
"lines-around-comment": [          // require empty lines around comments  [AUTOFIX]
  2,
  {
    "beforeBlockComment": false,   // I would actually do the opposite 
    "beforeLineComment": false     // I would actually do the opposite 
  }
],
```

Inline comments are disabled, I think.

```
"no-path-concat": 2,               // disallow string concatenation with __dirname and __filename
                                   // Change to 0
"no-process-env": 2,               // disallow the use of process.env
                                   // Change to 0
```

Sure.

```
"object-curly-spacing": [         // enforce consistent spacing inside braces  [AUTOFIX]
  0,
  "never"                         // We have been enforcing it up until now [2, "always"]
]
```

Not strongly opinionated on this.

**Comment by carpasse** [comment]
Ok I have reviewed the rules with @gajus 

Agreed to leave as they are

``` javascript
"array-callback-return": 2,         // enforce return statements in callbacks of array methods
                                    // ??? Will this work with shorthand arrow functions?
                                    // Yes it will


"consistent-return": 2,             // require return statements to either always or never specify values
                                    // Doesn't this rule conflicts with "callback-return" style rule?? 
                                    // NOPE it allows "callback-return" styles


"generator-star-spacing": [         // enforce consistent spacing around * operators in generator functions  [AUTOFIX]
   0,                               // Souldn't it be error? 
   {                                // Enforced by another rule
     "after": false,
     "before": true
   }
],

"import/imports-first": [          // UNKNOWN RULE  <==== where is this rule
  2,                               // Gajus will remove this in canonical
  {
    "absolute-first": true
  }
],

"import/no-namespace": 2,          // Report namespace imports
                                   // See no reason for forbidding namespaces on imports
                                   // The reason is that it breaks static analysis

"no-path-concat": 2,               // disallow string concatenation with __dirname and __filename
                                   // Change to 0
                                   // You should use 'path'


"no-process-env": 2,               // disallow the use of process.env
                                   // Change to 0
                                   // The use process.env should be explicitly enabled in the config file
```

Pending

``` javascript
"consistent-this": [                // enforce consistent naming when capturing the current execution context
    2,
    "self"                          // We can not use "self" it has a meaning on the browsers, use _this instead
],

"import/default": 2,               // Ensure a default export is present, given a default import.
                                   // Won't we get a lot of false possitive with this rule on projects that don't use import/export?


"lines-around-comment": [          // require empty lines around comments  [AUTOFIX]
  2,
  {
    "beforeBlockComment": false,   // I would actually do the opposite 
    "beforeLineComment": false     // I would actually do the opposite 
  }
],

"object-curly-spacing": [         // enforce consistent spacing inside braces  [AUTOFIX]
  0,
  "never"                         // We have been enforcing it up until now [2, "always"]
]
```

**Comment by claudiorodriguez** [comment]
- `consistent-this`: no opinion, I usually go for arrow funcs in that situation
- `import/default`: I see no problem, we should leave this as is
- `lines-around-comment`: I had no issue with comment rules as they are so far, we should leave them as is, IMHO
- `object-curly-spacing`: I used to prefer spacing, but I got used to no space. This is an autofix rule so whatever. I vote for no spacing, but don't care.

**Comment by gajus** [comment]
``` js
"object-curly-spacing": [         // enforce consistent spacing inside braces  [AUTOFIX]
  0,
  "never"                         // We have been enforcing it up until now [2, "always"]
]
```

It is enforced:

https://github.com/gajus/eslint-config-canonical/blob/d8965a4d8f60e0b3eb8db8d894e50c012314a72b/eslintrc.json#L89-L92

**Comment by carpasse** [comment]
My bad It is enforced

**Comment by gajus** [comment]
> - Enable template literals

I dislike template literals for several reasons:
- It does not allow to define a custom escape sequence. As a result, you have no guarantee that a multi-line string will work. (Incompleteness argument)
- Template literals cannot be used everywhere, e.g. you cannot use them to declare ES imports. Therefore, unlike single or double quotes, they cannot be enforced to be used for everything. (Consistency argument)
- It is being abused for no good reason - I have already seen a lot of code (in @mol-fe) that uses template string for no good reason, e.g. declaring test cases: `it(`runs code`)`.

Therefore, I like to throw error about template literals and allow the developer to enable them per use case/ per file as they become needed. They do have a use-case (multi-line strings) and I am using them for this purpose, e.g. https://github.com/gajus/eslint-plugin-jsdoc/blob/1339f8ea05f9f1fef01bd257c8dac330cef2c024/tests/rules/assertions/requireHyphenBeforeParamDescription.js#L7-L12.

This rule is primarily to prevent unnecessary use of literal strings and this way promote consistency.

> - Enable shorthand arrow funcs

I personally find code like `a => b => c => a(b(c))` unreadable VS

``` js
(a) => {
    return (b) => {
        return (c) => {
            return a(b(c));
        }
    };
};
```

But this is just personal preference.

> - Enable commonjs imports

Discussed with Carlos. To re-iterate:

This is done to discourage use of commonjs imports in future projects. If you need to use commonjs (e.g. runtime imports) enable it for that use case/ file.

> - Disable strict checking

This rule ensures that developers do not write `"use strict"` in the code by hand. If you are using webpack, it will be inserted for you automatically and enforced throughout the code base. Leaving it up to the developer to add `"use strict"` makes it vulnerable to accidental oversights.

> - Enable native promise

Regarding `"promise/no-native": "off",`

This rule is not meant to discourage using of Promises. It is only here to ensure that you do not accidentally use Promises in ES5 project.

However, if it is assumed that all environments will have Promises polyfilled, it is safe to disable this rule.

> - Disable lodash typechecking

This has been disabled in v1.9.0 https://github.com/gajus/eslint-config-canonical/tree/v1.9.0.

You can still enable lodash rules using:

``` json
{
  "extends": [
    "canonical",
    "canonical/lodash"
  ]
}
```

> "import/default": 2,               // Ensure a default export is present, given a default import.
>                                   // Won't we get a lot of false possitive with this rule on projects that don't use import/export?

You have missed the following in the documentation:

> A module path that is ignored or not unambiguously an ES module will not be reported when imported.

(see: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md)

> consistent-this: no opinion, I usually go for arrow funcs in that situation

My preference is "self".

Declaring "self" does not cause issues with IE. (See http://stackoverflow.com/a/12013524/368691) (Not to be confused with attempting to overwrite the value of the global variable.)

> "lines-around-comment": [          // require empty lines around comments  [AUTOFIX]
>   2,
>   {
>     "beforeBlockComment": false,   // I would actually do the opposite 
>     "beforeLineComment": false     // I would actually do the opposite 
>   }
> ],

There was a reason why I have done it this way... But I cannot remember it anymore.

This has been changed in [v1.10.0](https://github.com/gajus/eslint-config-canonical/tree/v1.10.0) to:

``` json
"lines-around-comment": [
  2,
  {
    "allowArrayEnd": true,
    "allowArrayStart": true,
    "allowBlockEnd": true,
    "allowBlockStart": true,
    "allowObjectEnd": true,
    "allowObjectStart": true,
    "beforeBlockComment": true,
    "beforeLineComment": true
  }
],
```

**Comment by gajus** [comment]
Other notes:
- This PR adds:
  
  > "max-len": [2, 120],
  
  This has been done, [v1.12.0](https://github.com/gajus/eslint-config-canonical/tree/v1.11.0).
  
  To be precise, I have chose to use 160 (2 \* regular standard).
- This PR adds
  
  > "react/forbid-component-props": "off",
  
  Whats the reason for wanting to disable this rule?
- RE: `"no-path-concat": 2,`
  
  I have explained to Carlos the purpose of this rule.
  
  It does not restrict using __dirname, etc. It restricts of string concatenation with these constants, e.g.
  
  BAD: `__dirname + '/foo'`
  GOOD: `path.join(__dirname, 'foo')`
- RE: `"no-process-env": 2,`
  
  This is done to ensure that `process.env` is used sparingly, ideally only in 1 file, e.g. `./config.js`.
  
  Disable this rule per-file.

**Comment by gajus** [comment]
To summarise, this PR should only change (assuming `"react/forbid-component-props": "off",` was added by an error):

``` diff
{
      "extends": "canonical",
      "rules": {
+        "arrow-body-style": "off",
+        "no-restricted-syntax": "off",
+        "promise/no-native": "off",
      }
  }
```

**Comment by gajus** [comment]
Regarding `object-curly-spacing` rule, there is an open discussion here.

https://github.com/MailOnline/eslint-config-mailonline/issues/3

Please cast your everyone, @MailOnline/mol-fe .

**Comment by claudiorodriguez** [comment]
> Whats the reason for wanting to disable this rule? (forbid-component-props)

To allow `style` as a prop, for `material-ui`. I'm fine adding it on a per-project basis.

**Comment by gajus** [comment]
> > Whats the reason for wanting to disable this rule? (forbid-component-props)
> 
> To allow style as a prop, for material-ui. I'm fine adding it on a per-project basis.

As you have suggested, I'd prefer to see this set per-project basis.

**Comment by gajus** [comment]
@carpasse to answer your future comment (I am oracle!):

If you settle on `_this`, then you will also need to disable `id-match`.

https://github.com/gajus/eslint-config-canonical/blob/0012b69178974a4536cb4948f0cf28b60305880b/configurations/eslintrc.json#L220-L227

`id-match` enforces variables names that comply with:

``` js
(^[A-Za-z]+(?:[A-Z][a-z]*)*\\d*$)|(^[A-Z]+(_[A-Z]+)*(_\\d$)*$)|(^(_|\\$)$)
```

and ... it is designed to restrict use of non-semantic naming conventions such as `_this`. :-)

**Comment by carpasse** [comment]
``` javascript
"consistent-this": [                // enforce consistent naming when capturing the current execution context
    2,
    "self"                          // We can not use "self" it has a meaning on the browsers, use _this instead
],
```

My vote still goes for `_this`. We are using on other mol-fe projects, it is defined on the window obj and it is my personal preference :P 

``` javascript
"import/default": 2,               // Ensure a default export is present, given a default import.
                                   // Won't we get a lot of false positive with this rule on projects that don't use import/export?
```

Ok with leaving this as it since you did not have conflicts

**Comment by carpasse** [comment]
@gajus fiiiiiiiiiine use `self`

**Comment by A0dh** [comment]
`sort-keys` do not autofix for me. Does it make sense to have it enabled?

**Comment by A0dh** [comment]
`no-inline-comments` - I think sometimes they can be useful
`init-declarations` - I find it annoying

**Comment by gajus** [comment]
> sort-keys do not autofix for me. Does it make sense to have it enabled?

I would very much have it enabled. :-)

I genuinely think it is the best rule in the entire rule set, and one that had the most positive impact to my coding.

**Comment by claudiorodriguez** [comment]
`init-declarations` is, IMHO, essential to ensure that if you're using `let` you're using it properly.

**Comment by gajus** [comment]
> no-inline-comments - I think sometimes they can be useful

Just write them above the subject, i.e. instead of

``` js
foo(); // calling foo
```

write

``` js
// calling foo
foo();
```

This separates code from comments and allows easier scanning of the code.

**Comment by ikhemissi** [comment]
> > no-inline-comments - I think sometimes they can be useful
> 
> Just write them above the subject, i.e. instead of

Well, I think they should not be removed, if you chain promises (to illustrate a workflow) it makes more sense to put comments on the same line.

I couldn't finish reviewing all the rules, but here are my concerns/notes about the current rule set (feel free to ignore them and proceed as I'm not working today so I cannot defend whatsoever rule):

Why do we have these rules  (and should we keep them) ?
- “objectLiteralComputedProperties": true, https://leanpub.com/understandinges6/read#leanpub-auto-duplicate-object-literal-properties
- "objectLiteralShorthan”: true, https://github.com/lukehoban/es6features#binary-and-octal-literals
- “superInFunctions”: true, // do we really need this ? shouldn’t be enabled per file if needed ?
- block-scoped-var —>  we already have “no-var”  http://eslint.org/docs/rules/no-var
- no-catch-shadow —> I don’t think we will ever need this as we don’t support IE8

I would rather have have a different value for these rules:
- eslint arrow-body-style: ["error", "as-needed"]  http://eslint.org/docs/rules/arrow-body-style#as-needed
- brace-style —> use “1tbs” but not with “allowSingleLine”: false (default settings in Eslint), we have arrow function to help with ”short” functions.
- comma-dangle —> comma-dangle: ["error", "only-multiline"] // we already had this discussion before but I still wanted to mention it http://eslint.org/docs/rules/comma-dangle#only-multiline :-(
-  func-style —> ["error", "declaration", { "allowArrowFunctions": true }]  http://eslint.org/docs/rules/func-style#declaration
- guard-for-in  —> disable this rule  http://eslint.org/docs/rules/guard-for-in
- id-length  —> I'm not convinced we should not allow a developer to write `x` when it comes to a coordinate x and forcing that to `coordinateX`, for example.
- id-match —> disable this rule or change it with it if we are gonna use eslint with jQuery projects because you cannot name your variables `$content = $(selector)` if you want to. // http://stackoverflow.com/questions/3360858/why-use-in-the-name-of-javascript-variables#3360883
- init-declarations —> disable this rule, it makes things complicated
- line-comment-position —> disable this rule. I think there is benefits in using line comments, when we need them.
- lines-around-comment —> lines-around-comment: ["error", { "beforeBlockComment": true, “beforeLineComment”: true }]
- "max-len": 1 —> max-len: [1, 200]
- no-confusing-arrow —> disable this rule, it makes code verbose 
- no-console —> disable this rule, we are using console to log data on node apps, but not in browsers

Unfortunately, I only went through 50% of rules :-( 
Once again, feel free to ignore these comments and proceed if you think they are not needed.

**Comment by gajus** [comment]
Thank you for the comments @ikhemissi 

> “objectLiteralComputedProperties": true, https://leanpub.com/understandinges6/read#leanpub-auto-duplicate-object-literal-properties
> "objectLiteralShorthan”: true, https://github.com/lukehoban/es6features#binary-and-octal-literals
> “superInFunctions”: true, // do we really need this ? shouldn’t be enabled per file if needed ?

There are irrelevant since ESLint added ES2017 support.

https://github.com/gajus/eslint-config-canonical/commit/11d152b7501e16032c5f0955b64fd6f417d76812

> block-scoped-var —> we already have “no-var” http://eslint.org/docs/rules/no-var

A developer might choose to disable `no-var` per-project (e.g. legacy). In which case, the other relevant rules will kick-in.

> no-catch-shadow —> I don’t think we will ever need this as we don’t support IE8

Doesn't hurt to have it.

> eslint arrow-body-style: ["error", "as-needed"] http://eslint.org/docs/rules/arrow-body-style#as-needed

Agreed. I'd prefer "as-needed" over just disabling the rule.

> brace-style —> use “1tbs” but not with “allowSingleLine”: false (default settings in Eslint), we have arrow function to help with ”short” functions.

Disagree. However, style preference.

> comma-dangle —> comma-dangle: ["error", "only-multiline"] // we already had this discussion before but I still wanted to mention it http://eslint.org/docs/rules/comma-dangle#only-multiline :-(

comma-dangle is now allowed. https://github.com/gajus/eslint-config-canonical/blob/11d152b7501e16032c5f0955b64fd6f417d76812/configurations/eslintrc.json#L93-L96

Are you proposing to allow it? I have no problems with that. Please raise a vote, https://github.com/MailOnline/eslint-config-mailonline/issues/8.

> comma-dangle —> comma-dangle: ["error", "only-multiline"] // we already had this discussion before but I still wanted to mention it http://eslint.org/docs/rules/comma-dangle#only-multiline :-(

No way. :-) Hoisting leads to horrible bugs. But, there is vote thread to express preferences.

> guard-for-in —> disable this rule http://eslint.org/docs/rules/guard-for-in

Please provide your reasoning.

> id-length —> I'm not convinced we should not allow a developer to write x when it comes to a coordinate x and forcing that to coordinateX, for example.

`coordinateX` is a lot more meaningful than `x`.

> id-match —> disable this rule or change it with it if we are gonna use eslint with jQuery projects because you cannot name your variables $content = $(selector) if you want to. // http://stackoverflow.com/questions/3360858/why-use-in-the-name-of-javascript-variables#3360883

If project is using jQuery, and you insist on this convention, you can disable rule just for that project. We are not actively using jQuery in new projects and a project dependency should not genera naming conventions (that said, I have added exceptions for use of `_` and `$` variable names).

Furthermore, that answer is a lie – there is no official jQuery convention to use `$` prefix for variables that represent a jQuery resource. The convention that the author probably refers to is for generated code only.

> init-declarations —> disable this rule, it makes things complicated

Might be the case. Please illustrate.

> line-comment-position —> disable this rule. I think there is benefits in using line comments, when we need them.

Might be the case. Please illustrate.

> lines-around-comment —> lines-around-comment: ["error", { "beforeBlockComment": true, “beforeLineComment”: true }]

This has been changed.

https://github.com/gajus/eslint-config-canonical/blob/11d152b7501e16032c5f0955b64fd6f417d76812/configurations/eslintrc.json#L323-L335

> "max-len": 1 —> max-len: [1, 200]

This has been changed (to 160, a multiple of the standard).

https://github.com/gajus/eslint-config-canonical/blob/11d152b7501e16032c5f0955b64fd6f417d76812/configurations/eslintrc.json#L340-L345

> no-confusing-arrow

I prefer verbosity over obscurity. This is a style preference, however. Please raise a vote.

> no-console —> disable this rule, we are using console to log data on node apps, but not in browsers

Disable per-line (using `// eslint-disable-next-line no-console` comment) when use is intended. It is designed to prevent leaking development leftovers.

Waiting for the other half. :-)

**Comment by brokenmass** [comment]
> eslint arrow-body-style: ["error", "as-needed"] http://eslint.org/docs/rules/arrow-body-style#as-needed

not opinionated 

> brace-style —> use “1tbs” but not with “allowSingleLine”: false (default settings in Eslint), we have arrow function to help with ”short” functions.

I agree we should remove the allowSingleLine

> comma-dangle —> comma-dangle: ["error", "only-multiline"] // we already had this discussion before but I still wanted to mention it http://eslint.org/docs/rules/comma-dangle#only-multiline :-

comma-dangle never is the way to go :D

> func-style —> ["error", "declaration", { "allowArrowFunctions": true }] http://eslint.org/docs/rules/func-style#declaration

expression style is coherent for both normal and arrow function. less exceptions, cleaner code

> guard-for-in —> disable this rule http://eslint.org/docs/rules/guard-for-in

we should avoid `for in` as much as possible and if used should be used properly and the rule is quite smart about it, so i would like to keep it

> id-length —> I'm not convinced we should not allow a developer to write x when it comes to a coordinate x and forcing that to coordinateX, for example.

not opinionated

> id-match —> disable this rule or change it with it if we are gonna use eslint with jQuery projects because you cannot name your variables $content = $(selector) if you want to. // http://stackoverflow.com/questions/3360858/why-use-in-the-name-of-javascript-variables#3360883

you can disable on a per project basis and we are dropping jquery anyway

> init-declarations —> disable this rule, it makes things complicated

as long as you use const or let properly this rule will not make difference.

> line-comment-position —> disable this rule. I think there is benefits in using line comments, when we need them.

i think line comment tend to be complicate to manage. this rule is nice to separate comments from code (and stay in the max line length), and guarantee uniform code

> lines-around-comment —> lines-around-comment: ["error", { "beforeBlockComment": true, “beforeLineComment”: true }]

already changed in eslint-config-canonical

> "max-len": 1 —> max-len: [1, 200]

already changed in eslint-config-canonical

> no-confusing-arrow —> disable this rule, it makes code verbose

this rules is only for ambiguous situation. in that case verbosity is a plus !

> no-console —> disable this rule, we are using console to log data on node apps, but not in browsers

not sure about this. i understand it's usefulness in client side only project , but for server side code i think it's obsolete

**Comment by gajus** [comment]
> I agree we should remove the allowSingleLine

Please. Lets vote.

This suggestion is that we allow:

``` js
/*eslint brace-style: ["error", "1tbs", { "allowSingleLine": true }]*/

function nop() { return; }

if (foo) { bar(); }

if (foo) { bar(); } else { baz(); }

try { somethingRisky(); } catch(e) { handleError(); }
```

If think this introduces an unnecessary inconsistency in the code. You are sacrificing code consistency over 2 additional LoC, esp. given than it is rare to have single statement functions.

My biggest problem with "anything singleline" is that, e.g.

``` js
try { somethingRisky(); } catch(e) { handleError(); }
```

this entire line will be highligted in code version control every time regardless of whether you are changing the `try` block or the `catch` block.
- :+1: if you want to restrict `allowSingleLine` (require that opening and closing braces for a block are on separate lines)
- :-1: if you want to allow `allowSingleLine`

**Pull request merged**
