### PR TITLE
feat: relax promise/prefer-await rules

### PR DESCRIPTION
**Pull request by carpasse**
async/await is great and make the code more readable but it is not ideal for all situations.
Should IMHO be up to the developer to decide when to use it.

### CODE REVIEW

**Comment by claudiorodriguez** [comment]
The rule just produces a `warning` which for me is just an encouragement that can be ignored as necessary. I don't think we need to remove it, IMHO.

**Comment by carlosvillademor** [comment]
If we want to move towards async-await I would say to leave it. I agree with @claudiorodriguez that it will encourage people to update.

**Comment by carpasse** [comment]
For me it is async/await does not always work. Specially on the promise branching scenario
With that said if the team thinks otherwise the rule has been there long enough and we should enforce it if we want the code to use async/await as much as possible. I.E. set it as an Error and make this a breaking change.

To leave it as a warning is not doing much IMHO

**Comment by A0dh** [comment]
I would leave the warning

**Comment by hutber** [comment]
I would also prefer to leave it tbh. Sorry

**Comment by carpasse** [comment]
The teams seems to like the warning. Closing the PR

**Comment by ikhemissi** [comment]
I agree that this rule is not fit for all projects (mainly server-side projects).
This being said, I don't mind keeping things as it is if the team is not keen into changing anything (I'm disabling this rule in all server-side projects).

**Pull request closed without merging**
